#!/bin/bash
start_time=$(date +%s%N)
timeout %f java -Xmx%dm -cp /app Main < "/app/$1.in" || echo "exit code is $?" >&2
end_time=$(date +%s%N)
# 计算运行时间
execTime=$(( (end_time - start_time) / 1000000 ))
echo "execTime: $execTime"