spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /SandboxService
    username: SandboxService
    password: 123456
    listener:
      simple:
        prefetch: 1
  config:
    activate:
      on-profile: dev
