spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /SandboxService
    username: SandboxService
    password: 123456
    listener:
      simple:
        prefetch: 1

server:
  port: 8882

judge_system_id: "sample.judge0"